blank_issues_enabled: false
contact_links:
  - name: Clearpool Community Support
    url: https://github.com/orgs/clearpool-finance/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url:https://docs.clearpool.finance/clearpool/security/bug-bounty
    about: Please read more about security bug bounty here.